name = "slaterlibjl"
uuid = "f626ac06-0318-4850-8adf-601d70f8edcf"
authors = ["v1j4y <vijay.gopal.c@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"

[compat]
julia = "1.8.0"

[extras]
Test = "5d280331-652d-4c6a-8fb4-ee860eda7c06"

[targets]
test = ["Test"]
